### ISSUE TITLE
After using ObjectHub for a bit, there are 773 client objects

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#107]
Steps

- Browse around the IDE for a while, fork some objects, edit some data objects
- Do actions that trigger Hooks onChange events.

Findings

There are 773 instances of the Client object. Why? There should only be two or three.

**Comment by objecthub-io** [comment]
- Instances were only of JsClient - these are created every time a Client in the engine is ACCESSED not created
- Fixed bug in Micro App compilation that add dependent APPS parameters to window (missing var)
- Fixed bug in PlainHookPromiseImpl - close listener for client was installed twice but only released once.

**Comment by objecthub-io** [comment]
Fixed.
