### ISSUE TITLE
Request Domain: Services times out if SSL certificates have not been approved

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#111]
## Steps

- Request a new domain link with an SSL certificate
- In Step 2 it shows the button 'I have received the email and approved the request'
- Click this button BEFORE the request has been approved

## Findings

The following error is reported:

`2017-01-09T00:53:44.165Z ff67ebcb-d605-11e6-8d52-8752f49c998b Task timed out after 30.00 seconds`

**Comment by objecthub-io** [comment]
Fixed.
