### ISSUE TITLE
Pins in wrong order

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#136]
When adding a new pin, it appears at the BOTTOM of the pins screen, NOT at the top sometimes.

**Comment by objecthub-io** [comment]
This seems to work after issue with frequent server restarts had been fixed.

**Comment by stellardb** [comment]
This just happened again - Pins was not opened yet and an object was pinned in another window.

Upon opening the pins, the newly pinned object was displayed at the bottom of the list.

**Comment by objecthub-io** [comment]
Might happen when object was pinned in *the same window* as well.

**Comment by objecthub-io** [comment]
See issues #165.
