### ISSUE TITLE
Test Environment defining variable 'object' doesn't work

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#137]
## Steps

- Create a micro app which requires the variable 'object'.
- Create a test env with such a variable that is created by forking a referenced object.
- Select this test environment

## Findings

The exception is reported `(ReferenceError) : object is not defined`.

**Comment by mxro** [comment]
Issue seems to be when data-embed is used and the variables are referenced there, eg

```
<input data-embed='Value_Sync' data-node='object'>
```

**Comment by objecthub-io** [comment]
Fixed.
