### ISSUE TITLE
Usage display not initialized on first login

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#144]
The usage display in the header is not initialized when a user first signs in.

**Comment by mxro** [comment]
Also seems to be the same for second sign in with a new user.

**Comment by mxro** [comment]
Seems to have been caused by Database message processing not working, see [StellarDB Issue 79](https://github.com/stellardb/StellarDB/issues/79)

**Comment by objecthub-io** [comment]
Does seem to work now!
