### ISSUE TITLE
Exceptions from services sometimes not reported

### ISSUE THREAD

**Issue by stellardb** [objecthub-io/ObjectHub#158]
E.g. in reading out a zip file:

```
zipfile.openReadStream(entry, function(err, readStream) {
                            if (err) {
                                cb(err);
                                return;
                            }

// ERROR THROWN HERE
}
```

The error thrown within the handler is sometimes not recognized by the Micro Service.

**Comment by objecthub-io** [comment]
Tested, and errors within a setTimeout callback are handled, thus background exceptions should be caught.
