### ISSUE TITLE
Micro App Deploy Page: Links to Versions don't work

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#167]
When opening a specific version, by using the Link option, nothing is displayed.

**Comment by mxro** [comment]
Seems to be a problem with data not being committed during deployment process.

After set production version, it works.

**Comment by objecthub-io** [comment]
It seems to work sometimes for deploying the first version, but when deploying a second version, this version is empty until another commit is triggered?

**Comment by objecthub-io** [comment]
Fixed.
