### ISSUE TITLE
Value for CNAME not displayed in Domain Object

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#172]
# Steps

- Link a custom domain

(there was initially an error creating it at the step click 'confirm that ssl certificate confirmed')

# Findings

The field with the value for the CNAME is empty.

![cname](https://cloud.githubusercontent.com/assets/1448524/24281868/f827fc44-10af-11e7-8009-273b4d9860aa.PNG)

# Workaround

Reloading the page fixes the problem.

**Comment by objecthub-io** [comment]
Appears to work now.
