### ISSUE TITLE
After deleting all database from a Database object, the main database does not exist anymore.

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#183]
In a Database object, delete all child databases. Afterwards access database from a script.

The following error is reported:

```
Undefined: Link cannot be resolved. No node defined at address: [https://u1.objecthub.io/objecthub/home/my/~*2/data/.n/Instances/.n/User_Management/.n/Simple/.n/Backend/.n/Users/~d] java.lang.Exception: Undefined: Link cannot be resolved. No node defined at address: [https://u1.objecthub.io/objecthub/home/my/~*2/data/.n/Instances/.n/User_Management/.n/Simple/.n/Backend/.n/Users/~d]
```

**Comment by objecthub-io** [comment]
Does not seem to appear anymore.

**Comment by objecthub-io** [comment]
It still seems to happen, when accessing the database from a script.

Specifically, delete all dbs from the Session DB object in user management, and then run the Login server.

**Comment by objecthub-io** [comment]
It seems like while the database still exists, the NODE belonging to the database does not.

**Comment by objecthub-io** [comment]
Fixed.
