### ISSUE TITLE
'Please sign in' displayed on Micro Page on deployed version

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#193]
# Steps

- Create a Micro Page, Deploy
- Link Production Version to a Domain

# Findings

When opening the page through the domain, a 'Please Sign In' message appears.

**Comment by objecthub-io** [comment]
Micro Service `Perform Deploy` was changed to only fork data.

Thereby, the service would not contain the dependencies anymore and consequently the Micro Pages wouldn't neither.

**Comment by objecthub-io** [comment]
Fixed.
