### ISSUE TITLE
Usability - clicking 'Browser' covers a part of the home page

### ISSUE THREAD

**Issue by panditthecoder** [objecthub-io/ObjectHub#215]
Clicking on the 'Browser' link on https://objecthub.io/ide#/home covers a part of the home page and the contents are not visible. in order to read the rest of the line, one needs to minimize the popup.
2 suggestions
- make the sections variable width so the section is reformatted to word wrap around the new object
- make the popup a true popup so that the user can drag and or resize it within the browser frame.

**Comment by panditthecoder** [comment]
Actaully, after using the ide for a few days now, this is no longer an issue. just took some getting used to in the begining.

**Comment by objecthub-io** [comment]
Thank you for the update!

Closing this issue now!
