### ISSUE TITLE
Clicking on 'Edit' icon shows left pane multiple times.

### ISSUE THREAD

**Issue by panditthecoder** [objecthub-io/ObjectHub#219]
steps to recreate 
- Create a micro app
- log out
- open new tab and log into the ide
- click on the micro app
- click on the 'edit' icon (not the text) multiple times
output will be as in the attached file
![objecthub_edit_icon_issue](https://user-images.githubusercontent.com/29138377/26922542-0c26f2ca-4c5d-11e7-819d-f28926dfd205.JPG)

**Comment by objecthub-io** [comment]
Thank you for reporting the issue!

I can see from the screenshot that things don't look right there! I don't seem to be able to replicate this on my machine. Do you remember anything else you might have done that caused this? Was the micro app initially loading slow or fast?

In any case, we'll review the code which renders the micro app and see if there is something we can fix up to prevent this from happening.

**Comment by panditthecoder** [comment]
consistently able to reproduce it on my laptop
using chrome Version 58.0.3029.110 (64-bit)

- select any microapp or microservice so that the ide editor loads the code.
- click on icon next to any microapp or microservice to have the 'edit' 'trash' 'move' and 'rename' icons show up.
- triple click on the 'edit' icon or link.
- issue should be recreated
![objecthub_edit_icon_issue_new_pic](https://user-images.githubusercontent.com/29138377/26964404-e5f6aa0c-4d0e-11e7-865b-03c3569c9bd7.JPG)

**Comment by objecthub-io** [comment]
For some reasons, this does not happen on my test system. 

But I've made some changes of how the apps are displayed. Could you quickly test it again if this issues still occurs on your system? Thank you!!

**Comment by panditthecoder** [comment]
so the latest changes made seems to have fixed the issue as i am unable to recreate it any longer - was very consistant in recreation earlier.

**Comment by objecthub-io** [comment]
Thank you very much for checking!

It is great to know this does not happen anymore. Closing this issue now.
