### ISSUE TITLE
Deployed app appears compressed vertically

### ISSUE THREAD

**Issue by michaelbukachi** [objecthub-io/ObjectHub#223]
For some strange reason the deployed version of a microapp appears quite narrow.
You can check it out in this link:
https://u1.objecthub.io/michaelbukachi/home/my/~*3/deploy/main/~prod/page&secret=3eYPYQ1v

**Comment by objecthub-io** [comment]
Thank you for submitting this issue.

In your app, you use the following Bootstrap column: `<div class="col-lg-1">`. If you change this to something else, like `<div class="col-lg-8">`, the app shouldn't appear narrow anymore.

Does this solve the issue for you?

**Comment by michaelbukachi** [comment]
Oops. My bad. Thought I had specified `12` but it was one. It works now:). This issue can now be closed.

**Comment by objecthub-io** [comment]
Thank you for getting back!

Ok, closing the issue now!
