### ISSUE TITLE
cb function issue in iterating through arrays

### ISSUE THREAD

**Issue by panditthecoder** [objecthub-io/ObjectHub#225]
cb function has an issue iterating through arrays where the elements are named......

- using a microapp
- input is
 {
    Names:["Joe","Peter","Pan"]
}

### JS code
------------------
```
`var namerecd = [];
for (var i=0;i<input.Names.length;i++) {
    namerecd[i] = input.Names[i];
}
cb(null, {message: "this is the list " + namerecd });`
```
-------------------------
### Output /Result
-------------------------
{
    "message": "this is the list Joe,Peter,Pan"
}

### JS Code
----------------------------------
```
var namerecd = [];
for (var i=0;i<input.Names.length;i++) {
    // the variable i has been replaced with the identifier "name" in the next line
    namerecd["name"] = input.Names[i];
}
cb(null, {message: "this is the list " + namerecd });

```
### Output/Result
----------------------------------------
{
    "message": "this is the list "
}
--------------------------------------------------

**Comment by panditthecoder** [comment]
bad example. let me put in a better one

**Comment by objecthub-io** [comment]
Ok, thank you!
