### ISSUE TITLE
'Cannot display page' error does not display properly

### ISSUE THREAD

**Issue by GvozdenMiskovic** [objecthub-io/ObjectHub#227]
Clicking on the 'Documentation' button under 'Manage' in an empty MicroService object gives a "Cannot display page." error. However, it does not properly display the full error message when using the down arrow to display additional information. The crux of the issue is the fact that buttons are duplicated and displayed in seemingly incorrect locations. The below screenshots may clarify the situation. 

Error Message: 
![ss 2017-06-09 at 01 03 42](https://user-images.githubusercontent.com/14821089/26972912-1d5d1b98-4d14-11e7-9b70-0f5c6769ea77.png)

Error Message after pressing blue downward arrow: 
![ss 2017-06-09 at 01 04 38](https://user-images.githubusercontent.com/14821089/26972932-379db45e-4d14-11e7-905c-c228e5e07ef4.png)

Error Message after pressing the 'Show more...' after the blue arrow:

![ss 2017-06-09 at 01 05 17](https://user-images.githubusercontent.com/14821089/26972971-5d2d03e6-4d14-11e7-9db6-b980cd3d1979.png)

As you can see the 'Hide' and 'Show more...' buttons are duplicated and their location is scewed. In addition while both 'Show more...' buttons display the full error message only the leftmost 'Hide' button actually hides the error. 

This issue only occurs when using the blue downwards arrow rather than the original 'Show more...' button. The 'x' mark functions properly although it is impossible to recreate the error message once it is closed without reloading the page. 

UPDATE:

I've found that the above occurs with every error message that is displayed in this particular way.

**Comment by objecthub-io** [comment]
Thank you for reporting this issue.

It should be fixed now, the layout of the message display has been changed.

**Comment by objecthub-io** [comment]
Closing this issue.
