### ISSUE TITLE
Log In - 'Forgot my Password' request not working

### ISSUE THREAD

**Issue by GvozdenMiskovic** [objecthub-io/ObjectHub#228]
**Summary**
The option to reset the user password is currently not functioning properly. When attempting to request a password reset the following error is thrown "Cannot request password reset: No user with this email is registered in the system.". 

![ss 2017-06-09 at 06 20 29](https://user-images.githubusercontent.com/14821089/26984622-62ccf6e0-4d40-11e7-9448-84305d959ae7.png)

I have been able to reproduce this issue on two different accounts which have been registered through two separate gmail accounts.

**Comment by objecthub-io** [comment]
Thank you for reporting this issue!

I was able to reproduce this bug. The password reset did not work. It should be fixed now. Can you try it again?

**Comment by GvozdenMiskovic** [comment]
Hello,

I have just tried it again unfortunately it seems the issue has persisted. The same error message is displayed.

**Comment by objecthub-io** [comment]
Thank you for testing it again.

Sorry it still did not work. It should now be fixed for real. Could you try again?

**Comment by GvozdenMiskovic** [comment]
The issue has been fixed.

**Comment by objecthub-io** [comment]
Excellent! Thank you very much for checking :)

Will close this issue now!
