### ISSUE TITLE
UI/UX - Data object child creation menu disables

### ISSUE THREAD

**Issue by GvozdenMiskovic** [objecthub-io/ObjectHub#230]
**Summary**
When children for a Data Object the user is prompted with a sub-menu (below) to define the node path. One can choose to exit this sub-menu either by pressing the 'Cancel' button or by pressing the 'Escape' key on their keyboard. However, the latter permanently disables the 'Create' child button until the web page is reloaded.

![ss 2017-06-10 at 11 10 49](https://user-images.githubusercontent.com/14821089/27006358-612f827e-4e32-11e7-9124-63ec2331656b.png)

**Environment**
Windows 7
Chrome Version 59.0.3071.86 (Official Build) (64-bit)

**Steps to Reproduce**

- Create a new Data Object
- Press the 'Create' button
- Exit the 'Define Path' Sub-menu by pressing the 'escape' key on the keyboard
- Hover over the 'Create' button again without reloading the web page
- Reload the web page to fix

**Comment by objecthub-io** [comment]
Thank you for reporting this issue.

This should be fixed now.

**Comment by objecthub-io** [comment]
Closing this issue.
