### ISSUE TITLE
UI/UX - Object 'delete' button doesn't work in some cases

### ISSUE THREAD

**Issue by GvozdenMiskovic** [objecthub-io/ObjectHub#231]
**Summary**
In some cases the 'delete' option in the 'Browser' panel for objects doesn't work. Unfortunately, the cause of this issue has eluded me. It seems that this issue occurs randomly and I have been unable to find a reliable way of reproducing it.

**Comment by objecthub-io** [comment]
We were not able to reproduce this issue as of yet.

Closing this issue for now!
