### ISSUE TITLE
Download option generating error

### ISSUE THREAD

**Issue by NilotpalSenChowdhury** [objecthub-io/ObjectHub#233]
![track_v29503321](https://user-images.githubusercontent.com/7010037/27055550-6a979cfa-4fe2-11e7-8bbc-383a5bcbbad6.JPG)

**Details**:- Download option giving error under app deployment in OBJECTHUB

**Steps:-**
1)create a webservice object 
2)Go to deploy and enable deployment
3)click on the dowload button under share dropdown

**Comment by objecthub-io** [comment]
Thank you for reporting this issue!

We could confirm it and will address it in the next update.

**Comment by objecthub-io** [comment]
This should be fixed now.

**Comment by objecthub-io** [comment]
Closing this issue now.
