### ISSUE TITLE
Unable to move object from a folder back to the root folder

### ISSUE THREAD

**Issue by NilotpalSenChowdhury** [objecthub-io/ObjectHub#237]
Details  : -An object cannot be moved back to the root directory

Steps:- 
1)  Create a micro service object
2) Create a folder
3) Transfer the object to the folder
4) Now transfer the object back to the root  folder

No provision of transfering the object back to the main folder

**Comment by objecthub-io** [comment]
Thank you for reporting this!

I could confirm what you describe and we will fix this in the next update.

**Comment by objecthub-io** [comment]
This has been fixed now.

**Comment by objecthub-io** [comment]
Closing fixed issue.
