### ISSUE TITLE
'recent' tab in 'browser not giving correct info.

### ISSUE THREAD

**Issue by panditthecoder** [objecthub-io/ObjectHub#238]
The recent tab is not showing the recent apps or services i worked on rather it is showing the image given under.
could be caused by the recent changes related to #221 as I was testing that before this issue showed up.

![recent](https://user-images.githubusercontent.com/29138377/27150907-9040b2c2-5166-11e7-94c7-ba723032b5c9.JPG)

what i had done was
- created new micro app
- deleted it using the 'trash' icon
- as it was yet showing up in the editor side of the ide, clicked on deploy
- the ide froze on the deploying screen (as mentioned in my last comment) and i logged out of the ide, logged back in and saw the issue.
not sure if i can recreate it but from the looks of it, this should be a privileged screen and so should not be shown to normal users.

**Comment by objecthub-io** [comment]
Thank you for reporting this issue!

The recent screen indeed looks not correct on your screenshot. It should show a list of all the objects you have recently accessed. It seems like some error has happened in the IDE, which then lead to recent objects not being deployed correctly.

Could you try again in new browser window, hit reload after opening https://objecthub.io/ide and then open any object. Afterward, go to the recent tab. The object should show up correctly.

Apart from that, we still need to find a solution why this could happen i the first place.

**Comment by panditthecoder** [comment]
nope. yet see the issue.
I
- logged out of the ide
- exited the browser
- launched a new browser
- loaded the https://objecthub.io/ page and signed in
- clicked on a microapp called 'array issue' which loaded correctly
- clicked on 'recent' tab and the issue is yet there - see image
- BTW, the latest object (Arrayissue) does not show up in the recent list
![yet not fixed dbroot](https://user-images.githubusercontent.com/29138377/27177882-97ce98c2-51e5-11e7-9edf-a4789395bd2f.JPG)

**Comment by panditthecoder** [comment]
unfortunately, dbroot is making an appearance in the trash folder as well - see image
![db_root_in_trash_as_well](https://user-images.githubusercontent.com/29138377/27183588-b25c9bf0-51fc-11e7-8e4a-7e3b974a9911.JPG)

**Comment by panditthecoder** [comment]
looks like the dbroot issue is fixed. tried multiple combinations of create object, delete them before and after deploying, deleting others before and after deploying and none of them showed the dbroot object again -- so the changes seem to have fixed this. 
However, having another issue with the 'recent' tab. It is yet not showing up the correct information. will log another bug so that the issues can be handled appropriately

**Comment by objecthub-io** [comment]
Thank you for retesting it.

That is great news. Closing this issue now!
