### ISSUE TITLE
forked object does not show up in 'My Objects' tab in browser

### ISSUE THREAD

**Issue by panditthecoder** [objecthub-io/ObjectHub#246]
fork an object. It does not show up in the 'My Objects' tab - however, it does show up in the 'recent' tab. Logging out and logging back in makes the objects show up correctly in the lists.

**Comment by objecthub-io** [comment]
Thank you for reporting the issue.

We can confirm it and will fix it.

This has probably the same underlying cause as #244.

**Comment by objecthub-io** [comment]
This issue should be fixed now.

**Comment by panditthecoder** [comment]
This works as expected so we can close this specific issue. However, I will be logging another bug which has multiple anomalies in the listing in the browser pane. The fix for this issue may have triggered it so you may need to keep this open for a bit

**Comment by objecthub-io** [comment]
Thank you for retesting it.

The anomalies in the browser tabs are most likely a separate issue from this - so I will close this issue now!
