### ISSUE TITLE
Object renaming issue

### ISSUE THREAD

**Issue by DenisNedvigok** [objecthub-io/ObjectHub#248]
What: when you rename object new name does not appears in “My Objects” tab
Browser used: Google Chrome Version 58.0.3029.110 (64-bit)
How to perform:

- Create object in “My Objects” tab
- Rename object
- Review object’s name in “My Objects tab"

**Comment by objecthub-io** [comment]
Thank you for reporting this issue.

We could confirm it and will address it in a coming update.

**Comment by objecthub-io** [comment]
Duplicate of #245.
