### ISSUE TITLE
Trash not working

### ISSUE THREAD

**Issue by pranav-singhal** [objecthub-io/ObjectHub#253]
I deleted an object I had created by clicking the move to trash icon. When I restored it, it is no longer available in trash; but it is also not in my Browser's "my objects" section.
the object is called reaction_tester(mini game)
Although it is visible in my "recents" tab in the browser
Web Browser Used:  
Google Chrome: Version 59.0.3071.115 (Official Build) (64-bit)

1. create a micro app
2. move it to trash 
3. go to the trash folder by clicking on the user icon on the top right of the screen
4. in the trash folder, click on restore next to the object you just deleted.
here's a video
https://www.dropbox.com/s/s32pahmqjj3ssam/error.mov?dl=0

<img width="1274" alt="screen shot 2017-07-01 at 1 14 04 am" src="https://user-images.githubusercontent.com/29460541/27751594-a74a377c-5dfa-11e7-9780-f298e40e1e34.png">

**Comment by objecthub-io** [comment]
Thank you for reporting this issue.

We could confirm it and will address it in the next update. This only seems to happen for objects directly in 'My Objects' - objects in other folders can be restored.

**Comment by objecthub-io** [comment]
This has been fixed now.

**Comment by objecthub-io** [comment]
Fixing closed issue.
