### ISSUE TITLE
object with dependencies not publishing properly

### ISSUE THREAD

**Issue by pranav-singhal** [objecthub-io/ObjectHub#256]
I tried to add a dependency from the repo into my object and publish it
It seems to be working fine when I preview it in my browser but throws some js error when I access it from the repo
Here's a screen shot from when I preview it from the repo
<img width="1280" alt="screen shot 2017-07-01 at 2 54 31 pm" src="https://user-images.githubusercontent.com/29460541/27760793-8d40e632-5e6d-11e7-86f3-0c15805a4f1b.png">

Here's what it looks like in my IDE(Its working fine here)
<img width="1280" alt="screen shot 2017-07-01 at 2 54 52 pm" src="https://user-images.githubusercontent.com/29460541/27760804-cb67665c-5e6d-11e7-84d6-1b99397cb5e4.png">

From what I can tell, it is probably because I added a dependency from the forked version of an object from the repo.

**Comment by objecthub-io** [comment]
Thank you for reporting this issue!

From the error message it looks like that a public viewer (which the repo is) does not have access to one of the dependencies (so it is not public). Dependencies can be made public by releasing them to the repo. Please note that just releasing the dependency to the repo is not enough so currently. You will also need to replace the dependency in the app with one of the released versions of the dependency on the repo (see the object on the repo & then pin it). Hope this helps!

**Comment by objecthub-io** [comment]
Was this problem resolved for you?

**Comment by pranav-singhal** [comment]
yes
and thanks for the help!

**Comment by objecthub-io** [comment]
Thank you, closing this issue now!
