### ISSUE TITLE
Search in Repo needs fix

### ISSUE THREAD

**Issue by pranav-singhal** [objecthub-io/ObjectHub#260]
The search in repo is not working properly
If you try to search for something present in the repo right after you searched for something that is not present in the repo, the search does not refresh the result. 
This is what I did: 
1). Go to Repo
2). search for a random object that is not there
3). once the search results come back, try searching for an object that is for sure present in the repo
Here is a video of what the problem is:
https://www.dropbox.com/s/2a35b5uaf5d39rm/error_in_search.mov?dl=0

**Comment by objecthub-io** [comment]
Thank you for reporting this issue. We could confirm it and will address in the next update!

**Comment by objecthub-io** [comment]
This issue is fixed now.

**Comment by objecthub-io** [comment]
Closing fixed issue.
