### ISSUE TITLE
document.querySelector does not work as expected

### ISSUE THREAD

**Issue by DenisNedvigok** [objecthub-io/ObjectHub#262]
When you use document.querySelector with one item on the HTML markup in MicroApp (f.e. document.querySelector(‘button’)) chances are that you get some object that is not within your HTML markup.

Please refer example below:
HTML markup:
````
<html>
<body>
 <button type="button" class="btn btn-primary">Convert</button>
</body>
</html>
````
JavaScript:
````
app.init = function(cb) {
    console.log(document.querySelector('button'));
    cb();    
};
````
Console will show the button not from the HTML markup in HTML tab, but some other button from the DOM.

**Comment by objecthub-io** [comment]
Yes, the way that JS works requires to select elements in Micro Apps in a special way, by using the `$("button", elem)` selector.

More infos on the following page under the JavaScript section: https://objecthub.io/docs#/Micro_App

We can't really think of another way to restrict JS from only accessing a part of the DOM. Is there another option?

**Comment by objecthub-io** [comment]
Closing this issue now!
