### ISSUE TITLE
Release page is not being refreshed in timely manner

### ISSUE THREAD

**Issue by DenisNedvigok** [objecthub-io/ObjectHub#264]
When you click the ‘Publish New Version’ button in the ‘Release’ tab multiple times in a row the list in ‘Release History’ stops refreshing. Switching between tabs does not refresh list, it only refreshes after page refresh.
How to reperform: press ‘Publish New Version’ in ‘Release’ tab of MicroApp multiple times in a row.

**Comment by objecthub-io** [comment]
Thank you for reporting this issue.

We could confirm it and will fix it!

**Comment by objecthub-io** [comment]
This issue should be fixed now.

**Comment by objecthub-io** [comment]
Closing fixed issues.
