### ISSUE TITLE
Search ObjectHub Repository does not work as expected

### ISSUE THREAD

**Issue by DenisNedvigok** [objecthub-io/ObjectHub#265]
Search by tags requires too many characters to type. F.e.: I got a release with tag ‘**_converter_**’, it does not show in results when I type ‘con’ into search field. It takes one more character (‘**_conv_**’) in order to see the object in results.

**Comment by objecthub-io** [comment]
Thank you for reporting this issue.

Indeed something doesn't seem to be working quite right here. Strangely, the 'Converter' app does not show up when searching for 'con' - which should match the name of the Micro App. We will investigate.

**Comment by objecthub-io** [comment]
This should be fixed now.

**Comment by objecthub-io** [comment]
Closing fixed issues.
