### ISSUE TITLE
Repository link does not work as expected

### ISSUE THREAD

**Issue by DenisNedvigok** [objecthub-io/ObjectHub#267]
When you try to open link to the Repository object when logged out it opens with an error message.
Please refer image for more info.
![getauthorization](https://user-images.githubusercontent.com/12463408/27807917-e0a775b2-604c-11e7-858b-e3dd0927b72d.png)

Link shared: 
https://objecthub.io/ide#/object=https://r1.objecthub.io/objects/~Simple_Currency_Converter/versions/~*25/o

**Comment by objecthub-io** [comment]
Thank you for reporting this issue.

We could confirm it and will fix it!

**Comment by objecthub-io** [comment]
This has been fixed now.

**Comment by objecthub-io** [comment]
Closing fixed issue.
