### ISSUE TITLE
getting incorrect listing in "my Object" and "Recent" tabs.

### ISSUE THREAD

**Issue by panditthecoder** [objecthub-io/ObjectHub#270]

**Comment by panditthecoder** [comment]
see the attached images:
- the recent tab shows objects such as "bootstrap", "deploy" and "objecthub Web"
and "My Objects" tab listing a deleted app (see the one where the name is listed with the strikethrough font.

not sure if this is a result of fixing the 'fork' and 'rename' (#244,245 and 246) issue or a new one.
![deleted_oj_showing_up_in_my_objects](https://user-images.githubusercontent.com/29138377/28256903-2fd1e2fc-6ae4-11e7-9e37-671d354becf8.JPG)

![not_sure_if_this_should_be_here](https://user-images.githubusercontent.com/29138377/28256865-cccca700-6ae3-11e7-8380-49807949d3eb.JPG)

**Comment by objecthub-io** [comment]
Thank you for reporting this issue.

Very strange that these objects show up in your recent objects. We will have a look.

**Comment by objecthub-io** [comment]
We have removed the erroneous objects from your account. However, from the data it is not possible to see how these entries got there. Is there any chance you opened the 'Bootstrap 3.3.5 Default' objects and it went into the recent objects this way.

For the deleted object, they usually should be removed automatically from my objects upon deletion and I think generally this works - so we would need to know the specific way in which the object was deleted to proceed!

**Comment by panditthecoder** [comment]
do not recall the exact steps. let me try it again and if i succeed in getting the objects, i will list the steps.

**Comment by panditthecoder** [comment]
could not reproduce it. will try some more

**Comment by objecthub-io** [comment]
Closing issue.
