### ISSUE TITLE
Exception triggered while replacing the default wrapper

### ISSUE THREAD

**Issue by michaelbukachi** [objecthub-io/ObjectHub#274]
So I get an exception when I replace the default wrapper for a micro app with another (a forked one in this scenario). I've confirmed this multiple times.\
![screenshot from 2017-08-05 17-29-15](https://user-images.githubusercontent.com/10145850/29004524-65c8de7c-7ad1-11e7-80a4-7eb2b91d68ab.png)
![screenshot from 2017-08-05 17-30-00](https://user-images.githubusercontent.com/10145850/29004528-7aff9222-7ad1-11e7-8aec-32dba8e52d06.png)

**Comment by objecthub-io** [comment]
Thank you for reporting this issue.

This should be fixed now!

**Comment by objecthub-io** [comment]
Closing as fixed.
