### ISSUE TITLE
Security: Move User Data to Separate Domains

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#28]
At the moment, all user data is hosted on the domain objecthub.io. 

It will be safer to move user data to one domain per user, e.g. username.objecthub.io.

**Comment by mxro** [comment]
Create firewall for all users data on oh - if an oh cookie is present and the HTML node does not belong to user of the cookie, show a warning page that must be confirmed

**Comment by objecthub-io** [comment]
User data is now moved to its own domain: u1.objecthub.io.
