### ISSUE TITLE
Cannot create new user for App with User Management. Error Unauthorized: Insufficient authorization for database 

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#297]
When forking the App with User Management template, and then trying to register a new user, the following error occurs:

```
Unexpected error: Unauthorized: Insufficient authorization for database operation. java.lang.Exception: Unauthorized: Insufficient authorization for database operation.
Unknown.at bdc(Unknown Source)
Unknown.at Object.h$b(Unknown Source)
Unknown.at Object.n$b(Unknown Source)
Unknown.at PXe(Unknown Source)
Unknown.at Object.UXe [as fb](Unknown Source)
Unknown.at fYe(Unknown Source)
Unknown.at eYe(Unknown Source)
Unknown.at NXe(Unknown Source)
Unknown.at $5d(Unknown Source)
-end of stack trace
```

Access to the Users database works. This is caused by it not being able to access the Session IDs database.

**Comment by mxro** [comment]
This is fixed after the Get Token library is recompiled (e.g. one change has been done to the file.)

**Comment by objecthub-io** [comment]
Was an error with fork operation - the links for databases were not included in mapped nodes, e.g. the ~d nodes.
