### ISSUE TITLE
Cannot perfrom drop: (TypeError) : variableList.addVariable is not a function

### ISSUE THREAD

**Issue by michaelbukachi** [objecthub-io/ObjectHub#299]
I'm getting the error `Cannot perfrom drop: (TypeError) : variableList.addVariable is not a function` whenever I try to add an embedded micro app. The micro app doesn't get added after that.

**Comment by objecthub-io** [comment]
Thank you for reporting this issue.

It should be fixed now (after a reload of the page).

**Comment by objecthub-io** [comment]
Closing as fixed.
