### ISSUE TITLE
Copyright symbol doesn't render on deployed micro app.

### ISSUE THREAD

**Issue by michaelbukachi** [objecthub-io/ObjectHub#300]
The copyright doesn't get rendered on any browser. The encoding set is utf-8.
Both `&#9400;`  and `&copy;` don't work.  
![screenshot from 2017-08-31 17-51-45](https://user-images.githubusercontent.com/10145850/29929808-34b688b8-8e75-11e7-945c-1b866c51df23.png)

**Comment by objecthub-io** [comment]
This should be fixed now.

**Comment by objecthub-io** [comment]
Closing as fixed.
