### ISSUE TITLE
Micro Service reports 503 error when submitting input with field userNodeUri

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#324]
# Steps

Supply a service with an input containing userNodeUri, eg.

```
{
  "userNodeUri" : "..",
  "userNodeSecret" : ".."
}
```

# Findings

The server reports a 503 error which does not state the problem clearly (e.g that this input variable is not allowed).

**Comment by objecthub-io** [comment]
Fixed.
