### ISSUE TITLE
Micro Services have persisted local Cache

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#49]
If AWS Lambda decides to keep the service alive, the local cache is persistent across sessions.

It might be better to clear the cache at the beginning of every invocation to achieve persistent behavior for every invocation.

Fix in JsSharedCache. Also make sure to use $wnd and not window.

**Comment by mxro** [comment]
Fixed.

**Comment by objecthub-io** [comment]
It seems that sometimes it takes a while until a change in a depended library is recognised.

**Comment by mxro** [comment]
Seems to apply to indirectly references libraries, e.g. libraries that are referenced by libraries used by the service.

**Comment by mxro** [comment]
Fixed.
