### ISSUE TITLE
Title for Forked Objects not set correctly

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#9]
Steps
- Fork an object with the new object button in a folder

Findings
- The title of the object is not correctly stored - it appears as if the object doesn't have a title (this happens sometimes)

**Comment by objecthub-io** [comment]
Seems to happen a lot when opening the same folder in two windows - then the windows where the folders are NOT created displays them incorrectly.

It seems the data is **created** correctly and **synchronized** correctly - but not displayed correctly in the list.

**Comment by objecthub-io** [comment]
Strangely, also is displayed incorrectly when opening in a NEW window?

**Comment by objecthub-io** [comment]
Found that problem is that root node for Object is not synchronized correctly to other screens.

It is synchronized as though it would have no children.

So '.meta' can never be found.

**Comment by objecthub-io** [comment]
Was caused by Stellar DB synchronization problem.
